version: '2'

services:
  app:
    image: 'app:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - flyway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/App3
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  flyway:
    container_name: my-flyway
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=password
      - FLYWAY_URL=jdbc:postgresql://db:5432/App3
      - FLYWAY_SCHEMAS=public
      - FLYWAY_GROUP=true
    image: flyway/flyway:latest
    command: migrate -url=jdbc:postgresql://db:5432/App3 -user=postgres -password=superPaha
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=App3